# Azure Web App / Databricks App configuration
# For Azure: these env vars are set via App Settings (portal or CLI), not this file
# For Databricks Apps: this file is used directly by the runtime

command:
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  # Databricks workspace URL (e.g. https://adb-xxxx.xx.azuredatabricks.net)
  - name: DATABRICKS_HOST
    value: ""

  # Databricks Service Principal credentials
  - name: DATABRICKS_CLIENT_ID
    value: ""
  - name: DATABRICKS_CLIENT_SECRET
    value: ""

  # Genie Space ID (from the Genie Space URL)
  - name: GENIE_SPACE_ID
    value: ""

  # Microsoft Entra ID auth (leave blank to disable -- useful for local dev)
  - name: AZURE_TENANT_ID
    value: ""
  - name: AZURE_CLIENT_ID
    value: ""

  # MLflow tracking URI (required when databricks-ai-bridge is installed)
  - name: MLFLOW_TRACKING_URI
    value: "databricks"

  - name: LOG_LEVEL
    value: "INFO"
