# Databricks Apps configuration
# DATABRICKS_HOST, DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET are auto-injected.

command:
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"

env:
  - name: GENIE_SPACE_ID
    value: ""

  - name: MLFLOW_TRACKING_URI
    value: "databricks"

  - name: LOG_LEVEL
    value: "INFO"
